theme: jekyll-theme-cayman
gems:
  - jekyll-seo-tag
title: Genel Seçimler için R Paketi
social:
  name: Berk Orbay
  links:
    - https://twitter.com/berkorbay
    - https://www.linkedin.com/in/berkorbay
